### ISSUE TITLE
Need scripts directory to train

### ISSUE THREAD

**Issue by rajasagashe** [pcyin/tranX#4]
The Readme says:
"The scripts folder contains scripts to train TranX on example datasets. For example, to train on the Django dataset, simply run: . scripts/django/train.sh 0 "

When will this be added?

**Comment by pcyin** [comment]
Hi! Please run `rull_data.sh` to download the example datasets and training scripts

**Comment by armheb** [comment]
after running rull_data.sh still can't train the django model, it finishes without an error but doesn't seem to do anything. what should I do?

**Comment by gsh2014** [comment]
same situation,have you solved this question


> after running rull_data.sh still can't train the django model, it finishes without an error but doesn't seem to do anything. what should I do?

**Comment by pcyin** [comment]
Hi all, sorry for the late reply! Could you try manually downloading `http://www.cs.cmu.edu/~pengchey/tranx.0.2.0.zip` and unzip it? The `scripts` folder is in the zip file :)

**Comment by gsh2014** [comment]
I have got the scripts,but as @armheb said it finished without an error,after I run the command "./scripts/atis/train.sh 0" . I think the scripts may have some problems. :)

**Comment by pcyin** [comment]
@gsh2014 Could you post your error message? Meanwhile, please make sure you use the correct `conda` environment to run the training script. `django` dataset only supports python 2.x

**Comment by gsh2014** [comment]
there is no error message at all , maybe the " python -u exp.py ..." in the "./scripts/atis/train.sh 0 " hasn't been excuted for some reason .

**Comment by pcyin** [comment]
This's weird. Could you check if `logs/django/${model_name}.log` exists, and if so, what's the content? Also, make sure the folder `logs/django` exists. `pull_data.sh` should generate it for you. You may also try commenting out the redirection, and post the standard output/err messages here.

**Comment by gsh2014** [comment]
`Namespace(action_embed_size=128, answer_prune=True, asdl_file='asdl/lang/lambda_dcs/lambda_asdl.txt', att_vec_size=256, batch_size=10, beam_size=5, clip_grad=5.0, column_att='affine', cuda=True, decay_lr_every_epoch=False, decode_max_time_step=110, decoder_word_dropout=0.3, dev_file='data/atis/dev.bin', dropout=0.3, embed_size=128, eval_top_pred_only=False, evaluator='default_evaluator', field_embed_size=32, glorot_init=True, glove_embed_path=None, hidden_size=256, lang='python', load_model=None, log_every=50, lr=0.001, lr_decay=0.5, lr_decay_after_epoch=0, lstm='lstm', max_epoch=-1, max_num_trial=5, mode='train', negative_sample_type='best', no_copy=True, no_input_feed=False, no_parent_field_embed=False, no_parent_field_type_embed=True, no_parent_production_embed=True, no_parent_state=False, no_query_vec_to_action_map=False, optimizer='Adam', parser='default_parser', patience=5, primitive_token_label_smoothing=0.1, ptrnet_hidden_dim=32, query_vec_to_action_diff_map=False, readout='identity', reset_optimizer=False, sample_size=5, save_all_models=False, save_decode_to=None, save_to='saved_models/atis/model.atis.sup.lstm.hidden256.embed128.action128.field32.type32.dropout0.3.lr_decay0.5.beam5.vocab.freq2.bin.train.bin.glorot.with_par_info.no_copy.ls0.1.seed0', seed=0, sql_db_file=None, src_token_label_smoothing=0.0, sup_attention=False, test_file=None, train_file='data/atis/train.bin', transition_system='lambda_dcs', type_embed_size=32, uniform_init=None, valid_every_epoch=1, valid_metric='acc', verbose=False, vocab='data/atis/vocab.freq2.bin', word_dropout=0.0)
Traceback (most recent call last):
  File "exp.py", line 251, in <module>
    train(args)
  File "exp.py", line 71, in train
    if args.cuda: model.cuda()
  File "/home/guishuo/anaconda3/envs/py3torch3cuda9/lib/python3.6/site-packages/torch/nn/modules/module.py", line 216, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/guishuo/anaconda3/envs/py3torch3cuda9/lib/python3.6/site-packages/torch/nn/modules/module.py", line 146, in _apply
    module._apply(fn)
  File "/home/guishuo/anaconda3/envs/py3torch3cuda9/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 123, in _apply
    self.flatten_parameters()
  File "/home/guishuo/anaconda3/envs/py3torch3cuda9/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 102, in flatten_parameters
    fn.rnn_desc = rnn.init_rnn_descriptor(fn, handle)
  File "/home/guishuo/anaconda3/envs/py3torch3cuda9/lib/python3.6/site-packages/torch/backends/cudnn/rnn.py", line 42, in init_rnn_descriptor
    cudnn.DropoutDescriptor(handle, dropout_p, fn.dropout_seed)
  File "/home/guishuo/anaconda3/envs/py3torch3cuda9/lib/python3.6/site-packages/torch/backends/cudnn/__init__.py", line 207, in __init__
    self._set(dropout, seed)
  File "/home/guishuo/anaconda3/envs/py3torch3cuda9/lib/python3.6/site-packages/torch/backends/cudnn/__init__.py", line 232, in _set
    ctypes.c_ulonglong(seed),
  File "/home/guishuo/anaconda3/envs/py3torch3cuda9/lib/python3.6/site-packages/torch/backends/cudnn/__init__.py", line 283, in check_error
    raise CuDNNError(status)
torch.backends.cudnn.CuDNNError: 8: b'CUDNN_STATUS_EXECUTION_FAILED'
`

**Comment by pcyin** [comment]
Hi @gsh2014, this might be a cuda-related issue, could you try updating your nvidia driver? Also, you could also try running the code on CPU without the `--cuda` flag.

**Comment by pcyin** [comment]
I am closing the issue since it might be platform/driver-related. Please feel free to re-open it!

**Comment by gsh2014** [comment]
thanks for your patience  :)
