### ISSUE TITLE
'ascii' codec can't decode byte 0xef in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by mynbo** [pcyin/tranX#43]
Traceback (most recent call last):
  File "/home/byang/gnrt/tranX/exp.py", line 569, in <module>
    train(args)
  File "/home/byang/gnrt/tranX/exp.py", line 47, in train
    train_set = Dataset.from_bin_file(args.train_file)
  File "/home/byang/gnrt/tranX/components/dataset.py", line 33, in from_bin_file
    examples = pickle.load(open(file_path, 'rb'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 0: ordinal not in range(128)

Have any suggestions for this problem?
the datasets downloading from http://www.cs.cmu.edu/~pengchey/tranx.0.2.0.zip.
and the tranx.0.2.1.zip.

the above dataset both have the Error ."ascii' codec can't decode byte 0xef in position 0: ordinal not in range(128)"

**Comment by mynbo** [comment]
This error appear on all datasets except conala
